# Generated by Django 4.2.3 on 2023-08-03 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200, verbose_name="Publisher's Name")),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=200, verbose_name='Publication Name')),
                ('publication_notes', models.CharField(blank=True, max_length=200, verbose_name='Publication Notes')),
                ('publication_type', models.CharField(choices=[('NEWSPAPER', 'Newspaper'), ('MAGAZINE', 'Magazine')], max_length=200, verbose_name='Publication Type')),
                ('publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cata.publisher')),
            ],
        ),
    ]
