# Generated by Django 4.2.3 on 2023-08-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keywords', models.TextField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_name', models.CharField(max_length=200)),
                ('author_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('edition_name', models.CharField(max_length=200)),
                ('edition_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=200)),
                ('tag_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
