# Generated by Django 4.2.3 on 2023-08-05 11:07

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0004_remove_article_created_at_alter_article_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='tag_name_unique',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='authorName',
        ),
        migrations.RenameField(
            model_name='edition',
            old_name='edition_name',
            new_name='editionName',
        ),
        migrations.RenameField(
            model_name='edition',
            old_name='publication_date',
            new_name='publicationDate',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_name',
            new_name='publicationName',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_notes',
            new_name='publicationNotes',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publication_type',
            new_name='publicationType',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publisher_name',
            new_name='publisherName',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='tagName',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_descriptor',
        ),
        migrations.AddField(
            model_name='article',
            name='articleName',
            field=models.CharField(default=0, max_length=200, verbose_name='Article Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tagDescriptor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(max_length=2000, verbose_name='Keywords'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('tagName'), name='tagNameUnique'),
        ),
    ]
