# Generated by Django 4.2.3 on 2023-08-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0005_remove_tag_tag_name_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='tagNameUnique',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='publicationType',
            new_name='publication_type',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publisherName',
            new_name='publisher_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='articleName',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='author',
            name='authorName',
        ),
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='author',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='editionName',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='id',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='publicationDate',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publicationName',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publicationNotes',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagDescriptor',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagName',
        ),
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='author_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='author_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edition',
            name='edition_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edition',
            name='edition_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_name',
            field=models.CharField(default=0, max_length=200, verbose_name='Publication Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Publication Notes'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(default=0),
        ),
    ]
