# Generated by Django 4.2.3 on 2023-08-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cata', '0006_remove_tag_tagnameunique_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
